"""Add ThreatIndicator Model

Revision ID: 03c83934cd76
Revises: ca74cae6a4c0
Create Date: 2025-12-15 01:30:42.717476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c83934cd76'
down_revision: Union[str, None] = 'ca74cae6a4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_value', sa.String(), nullable=False),
    sa.Column('indicator_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_indicators_id'), 'threat_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_threat_indicators_indicator_value'), 'threat_indicators', ['indicator_value'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_indicators_indicator_value'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_id'), table_name='threat_indicators')
    op.drop_table('threat_indicators')
    # ### end Alembic commands ###
