"""Add ForensicEvidence Model

Revision ID: 1075820f4ea8
Revises: dfc29a2f7560
Create Date: 2025-12-15 02:01:50.950183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1075820f4ea8'
down_revision: Union[str, None] = 'dfc29a2f7560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forensic_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('cryptographic_hash', sa.String(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forensic_evidence_id'), 'forensic_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_forensic_evidence_org_id'), 'forensic_evidence', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forensic_evidence_org_id'), table_name='forensic_evidence')
    op.drop_index(op.f('ix_forensic_evidence_id'), table_name='forensic_evidence')
    op.drop_table('forensic_evidence')
    # ### end Alembic commands ###
