"""Add AttackPrediction Model

Revision ID: 54e66b8f5604
Revises: 03c83934cd76
Create Date: 2025-12-15 01:34:13.567682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e66b8f5604'
down_revision: Union[str, None] = '03c83934cd76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('predicted_attack_type', sa.String(), nullable=False),
    sa.Column('target_asset', sa.String(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('time_horizon', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_predictions_id'), 'attack_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_attack_predictions_org_id'), 'attack_predictions', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attack_predictions_org_id'), table_name='attack_predictions')
    op.drop_index(op.f('ix_attack_predictions_id'), table_name='attack_predictions')
    op.drop_table('attack_predictions')
    # ### end Alembic commands ###
