"""Add DeceptionAsset Model

Revision ID: 98bea2da311e
Revises: 54e66b8f5604
Create Date: 2025-12-15 01:47:53.681330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98bea2da311e'
down_revision: Union[str, None] = '54e66b8f5604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deception_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('triggered_count', sa.Integer(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deception_assets_id'), 'deception_assets', ['id'], unique=False)
    op.create_index(op.f('ix_deception_assets_org_id'), 'deception_assets', ['org_id'], unique=False)
    op.create_index(op.f('ix_deception_assets_token'), 'deception_assets', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deception_assets_token'), table_name='deception_assets')
    op.drop_index(op.f('ix_deception_assets_org_id'), table_name='deception_assets')
    op.drop_index(op.f('ix_deception_assets_id'), table_name='deception_assets')
    op.drop_table('deception_assets')
    # ### end Alembic commands ###
