"""Add AttackerPersona Model

Revision ID: c667ac2d6b81
Revises: 98bea2da311e
Create Date: 2025-12-15 01:53:29.064747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c667ac2d6b81'
down_revision: Union[str, None] = '98bea2da311e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attacker_personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sophistication', sa.String(), nullable=True),
    sa.Column('related_ips', sa.JSON(), nullable=True),
    sa.Column('related_incidents', sa.JSON(), nullable=True),
    sa.Column('campaign_status', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attacker_personas_id'), 'attacker_personas', ['id'], unique=False)
    op.create_index(op.f('ix_attacker_personas_org_id'), 'attacker_personas', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attacker_personas_org_id'), table_name='attacker_personas')
    op.drop_index(op.f('ix_attacker_personas_id'), table_name='attacker_personas')
    op.drop_table('attacker_personas')
    # ### end Alembic commands ###
